language: ruby
rvm:
  - 1.8.7
services: memcache
env: 
  global: 
  - secure: |- # SALSA_TEST_USER
      Lm1ZCXwRTkOwD63f+C0fPcfWdN4ashTCW+DKHSCaAXh5yOx/SXXwYNxFoypg
      CUVuczYA2zuwOuuUh+bL+fPbDQ5/0F5h9gY2EUsTMIEcxM81gyDZT2R2HC64
      xAc24NPtza7mMDAYu2HiXIqZt0zW0fmPrh76KIzt/g9oxrnk9A0=
  - secure: |- # SALSA_TEST_PASS
      UaFkGJPSsMjML7M6toI+ZEq14ekXakjTHuRhyv9QVLSqMTKxmHwmzypyNySu
      FiZF4QuuWDa+y71Yvawbn5hDxtUGmqc9OCG8t3Mvv8oHmj0w1Taj+NsuC8hw
      oY3ycyFclfTQibOd9+Z2Kp+zp9GJoMqS96a1K0OqRCRXie7S4qA=
  - secure: |- # SALSA_TEST_NODE
      ZNh7VlEEECKc2/+XvsinItshI/wM+FQLfT1G5DCdSu7NQLTYbeJ/EcFUq/iG
      +gFn04gqye8c1GW7KHHbgKgi1gYGisqm//mnipylB3vfJeYkLhZab5/38JB0
      T+ig1DbDSJnnIo1MlxsxirgaeILmfacZ+eiWK5VlS+Mymy8emqI=
  - secure: |- # AWS_TEST_ACCESS_KEY_ID
      iRG9Wz7Sh44/Yk8DGsJZKuia2HNWLDHROT5cPLp1opbF4hMtwYOpsNjl471y
      uTyhQoslI0ePkj3cqGJeZsEl3gkURkw1/gi4kV11XdsMaMp/kBdH4hpw6SMI
      qCLnOuGqnOF2O3S8cwnneyPF8ixI2+xv6/iSHSVDBQwawDWtVLo=
  - secure: |- # AWS_TEST_SECRET_ACCESS_KEY
      hVnr8Qh6LW3HxKRsm3gNxUSjq8rBRAp1ddJm4UV9mih9awDOt9e6AMI97H2q
      Og1iPDcW5jTIjprDd5LwofDc2ZD5fs7y/CgQtzV6nJXZBvptmU63fLXNydO8
      klfhLMePkpsS+1dSlUCW+93UyRerKMjuV5Wdn89keFkNsk3jGYY=
  - secure: |- # AWS_TEST_DIR
      sYHSFJX74QpLTruob2cluW+v/Ez6th8mHfTbHFXvT2sCiSJkwU0XjzG8SKLY
      FOZZIndMBAjChWspC2rKBlPg0GYvsQaKAm3iHHLfjqFJSGuq0m2NdjJWWh+h
      shM3sxU/KbA4BwiimLcSkhW5xEA6C94gQqHiQIOeKy1Lxo4sKwo=
before_script:
  - mysql -e 'create database revent_test;'
  - cp config/examples/revent_config.rb.example config/revent_config.rb
  - cp config/examples/database.yml.example config/database.yml
  - "sed -i 's/username: revent/username: root/g' config/database.yml"
  - "sed -i 's/test_aws = false/test_aws = true/g' config/revent_config.rb"
  - "RAILS_ENV=test rake db:create db:schema:load"
script: rspec spec
