module EventImport
  ID_FIELD = 'MyCampaignID'
  NAME_FIELD = 'Event Name'
  SUBTITLE_FIELD = 'Subtitle'
  DESCRIPTION_FIELD = 'Event Description'
  SHORT_DESCRIPTION_FIELD = 'Short Description'
  DIRECTIONS_FIELD = ''
  LOCATION_FIELD = 'Address'
  STREET_NUMBER = 'Street No.'
  STREET_NUMBER_HALF = 'StreetNO Half'
  STREET_PREFIX = 'Street Prefix'
  STREET_NAME = 'Street Name'
  STREET_SUFFIX = 'Street Suffix'
  APT_TYPE = 'Apt Type'
  APT_NO = 'Apt No'
  CITY_FIELD = 'City'
  STATE_FIELD = 'State'
  POSTAL_CODE_FIELD = 'Zip'
  FB_EVENT_ID_FIELD = 'FB Event ID'
  START_DATE_FIELD = 'Start Date'
  START_TIME_FIELD = 'Start Time'
  END_DATE_FIELD = 'End Date'
  END_TIME_FIELD = 'End Time'
  HOST_NAME_FIELD = 'Event Host Name'
  HOST_FIRST_NAME_FIELD = 'First'
  HOST_LAST_NAME_FIELD = 'Last'
  HOST_EMAIL_FIELD = 'Event Host Email'
  HOST_PHONE_FIELD = ''
  ORG_NAME = 'Organization Name'
  EVENT_CUSTOM_ATTRIBUTE_FIELDS = {
    'sponsor_union' => '',
    'sponsor_local' => '',
    'sponsor_other' => 'Org Name'
  }
end
