#!/usr/bin/env bash

DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"
DATABASE_CONFIG=$DIR/config/database.yml
REVENT_CONFIG=$DIR/config/revent_config.rb
AMAZON_CONFIG=$DIR/config/amazon_s3.yml
SUPERUSERS=$DIR/config/superusers.yml

if [ ! -f $DATABASE_CONFIG ]; then
  cp $DIR/config/examples/database.yml.example $DATABASE_CONFIG
  echo "created $DATABASE_CONFIG"
else
  echo "$DATABASE_CONFIG already exisits"
fi

if [ ! -f $REVENT_CONFIG ]; then
  cp $DIR/config/examples/revent_config.rb.example $REVENT_CONFIG
  echo "created $REVENT_CONFIG"
else
  echo "$REVENT_CONFIG already exisits"
fi

if [ ! -f $AMAZON_CONFIG ]; then
  cp $DIR/config/examples/amazon_s3.yml.example $AMAZON_CONFIG
  echo "created $AMAZON_CONFIG"
else
  echo "$AMAZON_CONFIG already exisits"
fi

if [ ! -f $SUPERUSERS ]; then
  cp $DIR/config/examples/superusers.yml.example $SUPERUSERS
  echo "created $SUPERUSERS"
else
  echo "$SUPERUSERS already exisits"
fi
